# Generated by Django 5.2.7 on 2025-10-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='ingredient_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='recipe_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesmodel',
            name='source_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
