# Generated by Django 5.2.7 on 2025-10-27 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0002_alter_ingredientsmodel_ingredient_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientsourcesmodel',
            constraint=models.UniqueConstraint(fields=('ingredients', 'source'), name='unique_ingredient_source'),
        ),
        migrations.AddConstraint(
            model_name='recipesourcesmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'source'), name='unique_recipe_source'),
        ),
    ]
